// ─── Database client ─────────────────────────────────────────────────────────
export { db, getDriver, getPgPool, closeDb, type Database, type Driver } from "./client";

// ─── Advisory locking (cross-process serialization) ──────────────────────────
export { withAdvisoryLock, hashStringToInt } from "./advisory-lock";

// ─── Schema (table definitions) ──────────────────────────────────────────────
export * as schema from "./schema";
export type { ComposeServiceSpec, ServicePublicEndpoint } from "./schema/service";

// ─── Dump / restore (team-mode migration + project transfer) ─────────────────
export {
  dumpSubgraph,
  restoreSubgraph,
  deleteProjectSubgraph,
  dumpDatabase,
  restoreDatabase,
  DUMP_FORMAT_VERSION,
  PkCollisionError,
  ENCRYPTED_COLUMNS,
  stripEncryptedInPlace,
  type DatabaseDump,
  type DumpOptions,
  type RestoreOptions,
  type SubgraphScope,
} from "./dump";

// ─── Repositories (all DB access goes through here) ──────────────────────────
export {
  repos,
  createUserRepo,
  createSessionRepo,
  createAccountRepo,
  createGitInstallationRepo,
  createProjectAppRepo,
  createProjectRepo,
  createDeploymentRepo,
  createDomainRepo,
  createServiceRepo,
  createServiceDeploymentRepo,
  createPersonalAccessTokenRepo,
  normalizeRoutingFields,
  toComposeSpec,
  composeSpecsEqual,
  composeSpecDiff,
  createSettingsRepo,
  createServerRepo,
  createServerGithubAuthRepo,
  createGithubDeployKeyRepo,
  createServerTunnelRepo,
  createAnalyticsRepo,
  createTerminalSessionRepo,
  createServiceTerminalSessionRepo,
  type User,
  type NewUser,
  type Session,
  type Account,
  type GitInstallation,
  type NewGitInstallation,
  type ProjectApp,
  type NewProjectApp,
  type Project,
  type NewProject,
  type EnvVar,
  type NewEnvVar,
  type Deployment,
  type NewDeployment,
  type BuildSession,
  type NewBuildSession,
  type Domain,
  type NewDomain,
  type Service,
  type NewService,
  type ServiceDeployment,
  type NewServiceDeployment,
  type ServiceDeploymentStatus,
  type PersonalAccessToken,
  type PublicPersonalAccessToken,
  type NewPersonalAccessToken,
  type CreatePatInput,
  type UserSettings,
  type NewUserSettings,
  type Server,
  type NewServer,
  type ServerGithubAuth,
  type NewServerGithubAuth,
  type GithubDeployKey,
  type NewGithubDeployKey,
  type ServerTunnel,
  type NewServerTunnel,
  type ServerAnalyticsRow,
  type NewServerAnalytics,
  type ServerAnalyticsGeoRow,
  type NewServerAnalyticsGeo,
  type TerminalSession,
  type NewTerminalSession,
  type TerminalExitReason,
  type ServiceTerminalSession,
  type NewServiceTerminalSession,
  type BackupDestination,
  type NewBackupDestination,
  type BackupPolicy,
  type NewBackupPolicy,
  type BackupRun,
  type NewBackupRun,
  type BackupRestore,
  type NewBackupRestore,
  type BackupRunStatus,
  type BackupRestoreStatus,
  type DockerMigrationRun,
  type NewDockerMigrationRun,
  type DockerMigrationStatus,
  type Member,
  type MemberRole,
  type Invitation,
  type AuditEvent,
  type NewAuditEvent,
  createJobRunRepo,
  type JobRun,
  type NewJobRun,
  createJobRepo,
  type Job,
  type NewJob,
  type OrphanedResource,
  type NewOrphanedResource,
  type ResourceGrant,
  type Permission,
  type ResourceType,
  createNotificationChannelRepo,
  createNotificationSubscriptionRepo,
  createNotificationDefaultRepo,
  createNotificationDeliveryRepo,
  type NotificationChannel,
  type NotificationSubscription,
  type NotificationDefault,
  type NotificationDelivery,
  type ChannelKind,
  type DeliveryStatus,
} from "./repos";

// ─── Drizzle operators (re-exported for convenience) ─────────────────────────
export {
  eq,
  ne,
  and,
  or,
  not,
  gt,
  gte,
  lt,
  lte,
  like,
  ilike,
  inArray,
  notInArray,
  isNull,
  isNotNull,
  between,
  desc,
  asc,
  sql,
  count,
} from "drizzle-orm";
