import { pgTable, text, integer, boolean, timestamp, uniqueIndex, index } from "drizzle-orm/pg-core";
import { organization } from "./organization";
import { servers } from "./servers";

// ─── Per-server GitHub auth ───────────────────────────────────────────────────

/**
 * How ONE self-hosted server authenticates to GitHub for clone-on-server.
 *
 * This is the per-server GitHub identity the token resolver was missing:
 * `tokenFor`/`resolveBuildGitToken` consult this row when a clone runs on this
 * server. One row per server (unique `serverId`). Secrets are encrypted at rest
 * (enc1: field helpers) and decrypted only at deploy time — never logged, never
 * echoed by the API serializer. Cloud (CLOUD_MODE) never reads this table.
 *
 *   mode = "token"          → tokenEncrypted (from gh device-flow OR a pasted
 *                             per-server PAT); injected per clone like a PAT.
 *   mode = "ssh-server-key" → serverKeyPrivateEncrypted + serverKeyPublic; the
 *                             operator adds the public key to their GitHub
 *                             account once; clones over git@github.com.
 *   mode = "ssh-deploy-key" → keys live per-repo in `githubDeployKey`; this row
 *                             only records that deploy-key mode is selected.
 */
export const serverGithubAuth = pgTable(
  "server_github_auth",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    serverId: text("server_id")
      .notNull()
      .references(() => servers.id, { onDelete: "cascade" }),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),

    /** "token" | "ssh-server-key" | "ssh-deploy-key" */
    mode: text("mode").notNull(),

    // ── token mode ──
    tokenEncrypted: text("token_encrypted"),
    /** "device-flow" | "pat" — provenance, for the UI + audit. */
    tokenSource: text("token_source"),
    /** GitHub login the token belongs to (from a /user probe); display only. */
    tokenLogin: text("token_login"),

    // ── ssh-server-key mode ──
    serverKeyPrivateEncrypted: text("server_key_private_encrypted"),
    serverKeyPublic: text("server_key_public"),

    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    // One auth config per server — backs the upsert onConflictDoUpdate.
    uniqueIndex("uq_server_github_auth_server").on(t.serverId),
    index("idx_server_github_auth_org").on(t.organizationId),
  ],
);

/**
 * A GitHub deploy key generated by Openship for (server, owner, repo), used
 * when a server's auth mode is "ssh-deploy-key". The private key rides into the
 * clone; the public key is registered read-only on the repo via the GitHub API.
 * `githubKeyId` is the id returned by `POST /repos/{owner}/{repo}/keys`, kept so
 * we can DELETE it on disconnect / project teardown.
 */
export const githubDeployKey = pgTable(
  "github_deploy_key",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    serverId: text("server_id")
      .notNull()
      .references(() => servers.id, { onDelete: "cascade" }),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    owner: text("owner").notNull(),
    repo: text("repo").notNull(),
    /** id from GitHub's deploy-key API — for revocation. Null until registered. */
    githubKeyId: integer("github_key_id"),
    privateKeyEncrypted: text("private_key_encrypted").notNull(),
    publicKey: text("public_key").notNull(),
    readOnly: boolean("read_only").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_github_deploy_key_server_repo").on(t.serverId, t.owner, t.repo),
    index("idx_github_deploy_key_org_server").on(t.organizationId, t.serverId),
  ],
);
