#!/usr/bin/env bun
/**
 * Build a single, self-contained `apps/api/release-dist/` that ships
 * both the Openship API (raw TS, bun runs it directly) and the
 * dashboard (pre-built Next standalone). Ready to run with:
 *
 *     cd apps/api/release-dist
 *     bun install --production --frozen-lockfile
 *     bun run start.ts
 *
 * Why this exists:
 *
 * The migration wizard streams this dist to the operator's target
 * server. Pre-building it locally means the target does NOT need a
 * monorepo, turbo, the workspace catalog, or any build toolchain — it
 * just needs bun + a lockfile-locked install. The webmail dist
 * (`apps/email/scripts/build-release.ts`) follows the same pattern;
 * this is its sibling for the core platform.
 *
 * Output tree (canonical paths used by openship-dist.ts):
 *
 *   apps/api/release-dist/
 *     package.json        ← workspace-free, runtime deps only
 *     bun.lock            ← generated by `bun install` in dist root
 *     start.ts            ← supervisor: boots api + dashboard
 *     VERSION             ← <semver>\n<git-sha>\n<iso-date>\n
 *     README.md           ← run instructions for the operator
 *     api/
 *       package.json      ← workspace-free, file: refs to /packages/*
 *       src/              ← TS source (bun runs it directly)
 *       drizzle/          ← migrations, ran on first boot
 *     dashboard/
 *       server.js         ← Next standalone entry
 *       .next/            ← standalone build output (already minified)
 *       public/           ← static assets
 *     packages/
 *       core/             ← @repo/core source (workspace dep)
 *       db/               ← @repo/db source + drizzle/ migrations
 *       adapters/         ← @repo/adapters source (workspace dep)
 *
 * Workspace packages are copied verbatim and referenced via `file:`
 * paths in api/package.json. They are not on npm — shipping the
 * source is the only option. Bun runs TS directly so no build step is
 * needed for them.
 *
 * The script intentionally does NOT ship node_modules — the target's
 * `bun install --production --frozen-lockfile` reproduces the exact
 * graph from the shipped bun.lock.
 */

import { spawn, spawnSync } from "node:child_process";
import { cp, mkdir, rm, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const API_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = resolve(API_DIR, "../..");
const DASHBOARD_DIR = join(REPO_ROOT, "apps/dashboard");
const PACKAGES_DIR = join(REPO_ROOT, "packages");

/**
 * Workspace packages the API depends on at runtime. We ship the source
 * for each as a sibling under `packages/` inside the dist and rewrite
 * `workspace:*` references to `file:../packages/<name>`. Devluish packages
 * (db-email, ui, onboarding) aren't included — they're either dashboard-
 * only or webmail-only.
 */
const API_WORKSPACE_DEPS = ["core", "db", "adapters"] as const;

/**
 * Output directory. Defaults to `apps/api/release-dist/` (the canonical
 * path that `openship-dist.ts` resolves). Override via DIST_DIR for
 * concurrent CI builds.
 */
const DIST = process.env.DIST_DIR
  ? resolve(process.env.DIST_DIR)
  : join(API_DIR, "release-dist");

function log(msg: string): void {
  console.log(`[release] ${msg}`);
}

function run(cmd: string, cwd: string, env?: Record<string, string>): Promise<void> {
  return new Promise((res, rej) => {
    const child = spawn(cmd, {
      cwd,
      shell: true,
      stdio: "inherit",
      env: env ? { ...process.env, ...env } : process.env,
    });
    child.on("exit", (code) =>
      code === 0 ? res() : rej(new Error(`${cmd} (cwd=${cwd}) exited ${code}`)),
    );
  });
}

async function step<T>(label: string, fn: () => Promise<T>): Promise<T> {
  const t0 = performance.now();
  log(label);
  const out = await fn();
  log(`  ok ${(performance.now() - t0).toFixed(0)}ms`);
  return out;
}

async function readJson(path: string): Promise<Record<string, unknown>> {
  return JSON.parse(await readFile(path, "utf-8"));
}

async function writeJson(path: string, data: unknown): Promise<void> {
  await writeFile(path, JSON.stringify(data, null, 2) + "\n");
}

/**
 * Resolve the version pin every `workspace:*` dep should map to in the
 * release. For our `@repo/*` packages that means a relative `file:`
 * path to the sibling under release-dist/packages/. For third-party
 * deps that happen to use workspace protocols (none in this repo today,
 * but the check is cheap), we throw — those need explicit semver.
 *
 * `relPrefix` is the prefix relative to the package.json being
 * rewritten (e.g. ".." from api/, "../.." from packages/db/).
 */
function resolveWorkspaceDep(name: string, relPrefix: string): string {
  if (!name.startsWith("@repo/")) {
    throw new Error(
      `workspace:* dep "${name}" is not a @repo/* package; ` +
        `release build does not know how to resolve it`,
    );
  }
  const local = name.slice("@repo/".length);
  return `file:${relPrefix}/packages/${local}`;
}

/**
 * Rewrite a package.json's deps for the release dist:
 *   - workspace:*  -> file: path to sibling
 *   - keep semver  -> as-is
 *   - drop devDependencies entirely (release is runtime-only)
 *
 * `relPrefix` is how many directory levels up to walk from this
 * package.json to reach the dist root.
 */
function rewriteDeps(
  source: Record<string, unknown>,
  relPrefix: string,
): Record<string, string> {
  const out: Record<string, string> = {};
  const deps = (source.dependencies ?? {}) as Record<string, string>;
  for (const [k, v] of Object.entries(deps)) {
    if (typeof v !== "string") continue;
    if (v.startsWith("workspace:")) {
      out[k] = resolveWorkspaceDep(k, relPrefix);
    } else if (v.startsWith("catalog:")) {
      throw new Error(
        `catalog: protocol not supported in release build (dep "${k}": "${v}"). ` +
          `Pin to plain semver in the source package.json.`,
      );
    } else {
      out[k] = v;
    }
  }
  return out;
}

/**
 * Synthesize the API's release package.json. Same name + version, same
 * runtime deps, but workspace-coupling stripped and devDependencies
 * gone. The `start` script points at src/index.ts because bun runs TS
 * directly — no transpile step needed.
 */
async function buildApiPackageJson(): Promise<Record<string, unknown>> {
  const source = await readJson(join(API_DIR, "package.json"));
  return {
    name: source.name ?? "@repo/api",
    version: source.version ?? "0.0.0",
    private: true,
    type: "module",
    scripts: {
      start: "bun run src/index.ts",
    },
    // relPrefix ".." — api/ is one level deep, /packages is its sibling
    dependencies: rewriteDeps(source, ".."),
  };
}

/**
 * Synthesize a workspace package's release package.json. Same shape
 * (name/version/type/exports) but with workspace deps rewritten to
 * sibling file: paths. The `exports` map is preserved verbatim so
 * downstream imports (`@repo/db/schema`, `@repo/db/repos`, etc.)
 * resolve correctly when bun reads the package.
 *
 * Build/clean/lint scripts are dropped — the dist doesn't need them.
 */
async function buildWorkspacePackageJson(pkgName: string): Promise<Record<string, unknown>> {
  const source = await readJson(join(PACKAGES_DIR, pkgName, "package.json"));
  return {
    name: source.name,
    version: source.version ?? "0.0.0",
    private: true,
    type: source.type ?? "module",
    main: source.main,
    types: source.types,
    exports: source.exports,
    // relPrefix "../.." — packages/<name>/ is two levels deep
    dependencies: rewriteDeps(source, "../.."),
  };
}

/**
 * Read X.Y.Z from the monorepo root package.json — that file is the
 * single source of truth for the release version (mono-version repo).
 */
async function readRepoVersion(): Promise<string> {
  const pkg = await readJson(join(REPO_ROOT, "package.json"));
  return (pkg.version as string | undefined) ?? "0.0.0";
}

/**
 * Best-effort git sha. Returns "unknown" outside a git checkout (CI
 * shallow-clones, tarball builds, etc.). VERSION is informational —
 * never load-bearing — so a missing sha is fine.
 */
function gitSha(): string {
  const r = spawnSync("git", ["rev-parse", "HEAD"], {
    cwd: REPO_ROOT,
    encoding: "utf-8",
  });
  if (r.status !== 0) return "unknown";
  return (r.stdout ?? "").trim() || "unknown";
}

/**
 * ISO timestamp. Reproducible-build override: when SOURCE_DATE_EPOCH
 * is set (CI), use it so two builds from the same source produce
 * identical VERSION files. Otherwise, wall-clock.
 */
function isoDate(): string {
  const sde = process.env.SOURCE_DATE_EPOCH;
  if (sde) {
    const secs = Number.parseInt(sde, 10);
    if (Number.isFinite(secs)) return new Date(secs * 1000).toISOString();
  }
  return new Date().toISOString();
}

/**
 * Top-level release package.json. Holds nothing the operator runs
 * directly — `bun install` here installs api + dashboard runtime deps
 * (each is its own sub-package with a file:-linked workspace graph),
 * and `bun start` runs the supervisor.
 *
 * `workspaces` lists the sub-packages so a single `bun install` from
 * the root resolves the file: graph correctly (api -> packages/*).
 * Dashboard's standalone bundle already has its node_modules baked
 * in by `next build`, so it does NOT need to be a workspace member.
 */
function buildRootPackageJson(version: string): Record<string, unknown> {
  return {
    name: "@openship/release-dist",
    version,
    private: true,
    description:
      "Self-contained Openship release. Run `bun install --production --frozen-lockfile && bun run start.ts`.",
    type: "module",
    workspaces: ["api", "packages/*"],
    scripts: {
      start: "bun run start.ts",
    },
  };
}

const START_TS = `#!/usr/bin/env bun
/**
 * Release-dist supervisor. Boots the API and the dashboard as two
 * child processes under one parent, propagates signals, and exits
 * with the first non-zero child exit code.
 *
 * The two children are deliberately split:
 *   - api/ runs from raw TS via bun (no build step shipped).
 *   - dashboard/ runs the Next standalone bundle (already built).
 *
 * Both inherit the parent's env. Set API_PORT / DASHBOARD_PORT to
 * override the defaults. The dashboard's standalone server binds to
 * PORT, so we override it locally for the dashboard child only.
 */
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));

const apiPort = process.env.API_PORT ?? process.env.PORT ?? "4000";
const dashboardPort = process.env.DASHBOARD_PORT ?? "3000";

type Child = ReturnType<typeof spawn>;
const children: Child[] = [];

function start(name: string, cmd: string, args: string[], cwd: string, env: Record<string, string>): Child {
  const child = spawn(cmd, args, {
    cwd,
    stdio: "inherit",
    env: { ...process.env, ...env },
  });
  child.on("exit", (code, signal) => {
    console.log(\`[\${name}] exited code=\${code} signal=\${signal ?? ""}\`);
    // Bring the whole supervisor down if one child dies — keeps the
    // operator from staring at a half-up instance for hours.
    shutdown(code ?? 1);
  });
  children.push(child);
  return child;
}

let shuttingDown = false;
function shutdown(code: number): void {
  if (shuttingDown) return;
  shuttingDown = true;
  for (const c of children) {
    try { c.kill("SIGTERM"); } catch { /* ignore */ }
  }
  setTimeout(() => process.exit(code), 5_000).unref();
}

process.on("SIGTERM", () => shutdown(0));
process.on("SIGINT", () => shutdown(0));

// API: raw TS run by bun, from the api/ subdir (its package.json + the
// hoisted node_modules resolve from there).
start("api", "bun", ["run", "src/index.ts"], join(ROOT, "api"), {
  PORT: apiPort,
  // Dashboard talks to the API over loopback in this layout.
  API_INTERNAL_URL: \`http://127.0.0.1:\${apiPort}\`,
});

// Dashboard: Next standalone. The monorepo-rooted standalone lands at
// dashboard/apps/dashboard/server.js and expects to run from that dir so its
// relative .next/ + public/ + node_modules resolve.
start(
  "dashboard",
  "node",
  ["server.js"],
  join(ROOT, "dashboard", "apps", "dashboard"),
  {
    PORT: dashboardPort,
    HOSTNAME: "0.0.0.0",
  },
);
`;

const README = (version: string) => `# Openship release dist (v${version})

Self-contained release of the Openship platform (API + dashboard).
Designed to be streamed to a target server by the migration wizard,
or extracted manually for a fresh install.

## Run

\`\`\`bash
bun install --production --frozen-lockfile
bun run start.ts
\`\`\`

\`bun install\` reads the shipped \`bun.lock\` and reproduces the exact
dependency graph. \`--frozen-lockfile\` fails hard if the lockfile is
out of sync with the package.json — that's intentional, it catches
silent dep drift between dev and prod.

\`bun run start.ts\` boots the API and dashboard as two children under
one supervisor. SIGTERM/SIGINT bring both down. If either child exits
non-zero, the supervisor exits non-zero so systemd / docker can
restart cleanly.

## Ports

| Variable          | Default | Process    |
| ----------------- | ------- | ---------- |
| \`API_PORT\`        | \`4000\`  | api        |
| \`DASHBOARD_PORT\`  | \`3000\`  | dashboard  |

If \`API_PORT\` is unset, the supervisor falls back to \`PORT\`, then
to \`4000\`. The dashboard's \`API_INTERNAL_URL\` is wired to the API
port automatically.

## Layout

- \`api/\` — TS source, bun runs it directly. \`api/drizzle/\` migrations
  run on first boot via the API's normal migration path.
- \`dashboard/\` — Next standalone bundle. \`server.js\` is the entry.
- \`packages/\` — workspace packages the API depends on, linked into
  \`api/node_modules/@repo/*\` by bun via \`file:\` paths in api/package.json.
`;

async function main(): Promise<void> {
  log(`api dir   = ${API_DIR}`);
  log(`repo root = ${REPO_ROOT}`);
  log(`dist      = ${DIST}`);

  if (!existsSync(API_DIR) || !existsSync(DASHBOARD_DIR)) {
    throw new Error(
      `Missing apps/api or apps/dashboard — repo layout drift? ` +
        `Looked at ${API_DIR} and ${DASHBOARD_DIR}.`,
    );
  }
  for (const name of API_WORKSPACE_DEPS) {
    if (!existsSync(join(PACKAGES_DIR, name))) {
      throw new Error(`Missing workspace package: packages/${name}`);
    }
  }

  await step("cleaning previous release-dist/", async () => {
    await rm(DIST, { recursive: true, force: true });
    await mkdir(DIST, { recursive: true });
  });

  // 1. Build the dashboard. next.config.mjs already sets
  //    `output: "standalone"`, so .next/standalone/ contains a fully
  //    runnable server.js + a trimmed node_modules.
  //
  //    Force NODE_ENV=production: this runs via `bun run --cwd apps/api …`,
  //    and bun auto-loads apps/api/.env which sets NODE_ENV=development. A
  //    dev NODE_ENV leaking into `next build` loads React's dev build during
  //    the prod prerender → "/_global-error" crashes with a null useContext.
  //    The release is always a production, self-hosted (local, non-cloud)
  //    build regardless of the developer's ambient env.
  await step("building dashboard (next build, standalone)", async () => {
    await run("bun run build", DASHBOARD_DIR, {
      NODE_ENV: "production",
      CLOUD_MODE: "false",
      OPENSHIP_TARGET: "local",
    });
  });

  const dashboardStandalone = join(DASHBOARD_DIR, ".next/standalone");
  const dashboardStatic = join(DASHBOARD_DIR, ".next/static");
  const dashboardPublic = join(DASHBOARD_DIR, "public");
  if (!existsSync(dashboardStandalone)) {
    throw new Error(
      `Next standalone output missing — expected ${dashboardStandalone}. ` +
        `Check apps/dashboard/next.config.mjs has \`output: "standalone"\`.`,
    );
  }

  // 2. Copy the dashboard's standalone bundle. The standalone output
  //    is rooted at apps/dashboard inside .next/standalone/ — i.e. the
  //    layout matches the monorepo, with apps/dashboard/server.js as
  //    the entry. We flatten that into release-dist/dashboard/ so
  //    start.ts can point at it without knowing about apps/.
  //
  //    `.next/static` and `public/` are NOT included in standalone
  //    (Next's deliberate choice — assets are typically served by a
  //    CDN). We copy them in next to .next/ so the standalone server
  //    can serve them directly when no CDN is in front.
  await step("copying dashboard standalone to release-dist/dashboard/", async () => {
    const target = join(DIST, "dashboard");
    await mkdir(target, { recursive: true });
    // The monorepo-rooted standalone has the structure:
    //   .next/standalone/
    //     apps/dashboard/server.js
    //     apps/dashboard/.next/...
    //     node_modules/...
    //     package.json
    // We copy it all verbatim and then re-home server.js + .next/ at
    // the dist's dashboard/ root via a small shim (server-entry.js).
    // Simpler: copy the entire standalone tree into dashboard/ and
    // have start.ts launch apps/dashboard/server.js inside it.
    await cp(dashboardStandalone, target, { recursive: true });
    // Static assets need to sit at apps/dashboard/.next/static and
    // apps/dashboard/public so Next's standalone server finds them at
    // the paths it was built to expect.
    const innerNext = join(target, "apps/dashboard/.next");
    const innerPublic = join(target, "apps/dashboard/public");
    await mkdir(innerNext, { recursive: true });
    await cp(dashboardStatic, join(innerNext, "static"), { recursive: true });
    if (existsSync(dashboardPublic)) {
      await cp(dashboardPublic, innerPublic, { recursive: true });
    }
  });

  // 3. Copy api source + drizzle migrations. Drizzle migrations
  //    actually live in packages/db/drizzle/ in the monorepo, so they
  //    ship with the db package (step 4 below). The api/drizzle/ copy
  //    is also written so the API's migration loader can find them
  //    at the path it already expects.
  await step("copying api/src to release-dist/api/src/", async () => {
    const apiTarget = join(DIST, "api");
    await mkdir(apiTarget, { recursive: true });
    await cp(join(API_DIR, "src"), join(apiTarget, "src"), { recursive: true });
    await cp(
      join(API_DIR, "tsconfig.json"),
      join(apiTarget, "tsconfig.json"),
    );
    // Vendored static assets (e.g. the GeoLite2 DB) — geo-ip.ts resolves them
    // relative to the module, i.e. api/assets/ next to api/src/.
    if (existsSync(join(API_DIR, "assets"))) {
      await cp(join(API_DIR, "assets"), join(apiTarget, "assets"), { recursive: true });
    }
  });

  // 4. Copy each workspace package source + (for db) drizzle/. We
  //    drop dist/, node_modules/, .turbo/ if any leaked into the
  //    source tree.
  await step("copying workspace packages to release-dist/packages/", async () => {
    const pkgRoot = join(DIST, "packages");
    await mkdir(pkgRoot, { recursive: true });
    for (const name of API_WORKSPACE_DEPS) {
      const src = join(PACKAGES_DIR, name);
      const dst = join(pkgRoot, name);
      await mkdir(dst, { recursive: true });
      await cp(join(src, "src"), join(dst, "src"), { recursive: true });
      // Per-package tsconfig — bun reads it for path mapping at
      // runtime when present.
      if (existsSync(join(src, "tsconfig.json"))) {
        await cp(join(src, "tsconfig.json"), join(dst, "tsconfig.json"));
      }
      // Drizzle migrations live under packages/db/drizzle/ and are
      // loaded relative to the db package by the migration runner.
      // Copy verbatim — they're plain .sql + meta/_journal.json.
      if (name === "db") {
        const drizzleSrc = join(src, "drizzle");
        if (existsSync(drizzleSrc)) {
          await cp(drizzleSrc, join(dst, "drizzle"), { recursive: true });
        }
        if (existsSync(join(src, "drizzle.config.ts"))) {
          await cp(
            join(src, "drizzle.config.ts"),
            join(dst, "drizzle.config.ts"),
          );
        }
      }
    }
  });

  // 5. Synthesize workspace-free package.json files for api/ and each
  //    workspace package. workspace:* refs are rewritten to file:
  //    paths so a single `bun install` at the dist root resolves the
  //    whole graph without ever touching the monorepo.
  await step("writing release-dist/api/package.json", async () => {
    const pkg = await buildApiPackageJson();
    await writeJson(join(DIST, "api", "package.json"), pkg);
  });

  await step("writing release-dist/packages/*/package.json", async () => {
    for (const name of API_WORKSPACE_DEPS) {
      const pkg = await buildWorkspacePackageJson(name);
      await writeJson(join(DIST, "packages", name, "package.json"), pkg);
    }
  });

  // 6. Root package.json + start.ts. The root declares the workspace
  //    graph (api + packages/*) so `bun install` at root resolves the
  //    file: refs correctly.
  const version = await readRepoVersion();
  await step("writing release-dist/package.json + start.ts", async () => {
    await writeJson(join(DIST, "package.json"), buildRootPackageJson(version));
    await writeFile(join(DIST, "start.ts"), START_TS);
  });

  // 7. Generate the lockfile by running `bun install` at the dist
  //    root. Without a frozen lockfile the target re-resolves semver
  //    ranges on every deploy — silent drift between dev and prod is
  //    exactly the bug the webmail dist hit (0.3.4 silently resolving
  //    to 0.4.2 on the target). The lockfile pins exact versions.
  //
  //    We delete node_modules afterward; the lockfile is what travels
  //    with the dist, not the installed graph (which the target
  //    reproduces from the lock in seconds).
  await step("generating release-dist/bun.lock (no node_modules in dist)", async () => {
    await run("bun install", DIST);
  });
  await step("removing release-dist/node_modules + nested node_modules", async () => {
    await rm(join(DIST, "node_modules"), { recursive: true, force: true });
    // Workspace installs may have linked node_modules into api/ and
    // each packages/* dir. Strip them all — only bun.lock ships.
    for (const sub of ["api", ...API_WORKSPACE_DEPS.map((n) => `packages/${n}`)]) {
      await rm(join(DIST, sub, "node_modules"), { recursive: true, force: true });
    }
  });

  // 8. Stamp version metadata. VERSION is read by ops tooling to tell
  //    which build is running on a given host; README is for humans
  //    extracting the tarball.
  await step("writing VERSION + README.md", async () => {
    const sha = gitSha();
    const date = isoDate();
    await writeFile(join(DIST, "VERSION"), `${version}\n${sha}\n${date}\n`);
    await writeFile(join(DIST, "README.md"), README(version));
  });

  log("");
  log(`release dist at: ${DIST}`);
  log(`  version: ${version}`);
  log("");
  log("  cd apps/api/release-dist");
  log("  bun install --production --frozen-lockfile");
  log("  bun run start.ts");
}

main().catch((err) => {
  console.error("[release] FAILED:", err);
  process.exit(1);
});
